version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secret-key
      - WEB3_PROVIDER_URL=https://sepolia.infura.io/v3/100ce7ff2b694cf28bc062313e048bf0
      - FAUCET_PRIVATE_KEY=your-private-key
      - RATE_LIMIT_TIMEOUT=60
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres