version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
    - SECRET_KEY=django-insecure-_!f51pkw$4guwbpt)-ac7-39+la9*@rb6j!v0-53z7_szi&8xm
    - WEB3_PROVIDER_URL=https://sepolia.infura.io/v3/
    - FAUCET_PRIVATE_KEY=
    - RATE_LIMIT_TIMEOUT=60
    - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis  # Only redis dependency remains
    volumes:
      - .:/app  # For SQLite database persistence

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

# Removed PostgreSQL service and volume