# version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env  # This loads the environment variables from the .env file
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=faucet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: